name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        run: BROWSER="chrome"  
              BROWSER="chrome"
              if [ "$BROWSER" = "chrome" ]; then java -jar ./artifacts/app-order.jar --browser=chrome &
              elif [ "$BROWSER" = "firefox" ]; then java -jar ./artifacts/app-order.jar --browser=firefox &
              else    echo "Неизвестный браузер"
              exit 1
              fi
      - name: Build with Gradle
        run: ./gradlew test --info
     
    
